# Application Configuration
spring.application.name=api-gateway
server.port=8086

# Gateway Routes Configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# Eureka Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.default.slidingWindowSize=10
resilience4j.circuitbreaker.instances.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.default.waitDurationInOpenState=50s
resilience4j.circuitbreaker.instances.default.failureRateThreshold=50

# Centralized Swagger UI configuration for springdoc-openapi
springdoc.swagger-ui.urls[0].name=user-service
springdoc.swagger-ui.urls[0].url=/user-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=traininfo-service
springdoc.swagger-ui.urls[1].url=/traininfo-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=reservation-service
springdoc.swagger-ui.urls[2].url=/reservation-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=payment-service
springdoc.swagger-ui.urls[3].url=/payment-service/v3/api-docs

springdoc.swagger-ui.urls[4].name=admin-service
springdoc.swagger-ui.urls[4].url=/admin-service/v3/api-docs

# Allow access to Swagger UI and OpenAPI docs in gateway
spring.webflux.base-path=
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

